apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-helm
  labels:
    app: payment-api-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-api-helm
  template:
    metadata:
      labels:
        app: payment-api-helm
    spec:
      containers:
        - name: payment-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
